services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nest-api
      POSTGRES_USER: nest-api
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql:
