name: Evergreen

on:
  # schedule:
  # - cron: "* * * * *"
  workflow_dispatch:

jobs:
  evergreen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install packages
        run: yarn install --force

      - name: Audit packages
        id: audit_summary
        run: yarn audit --summary >> $GITHUB_OUTPUT

      - name: Build
        run: yarn build

      # - name: Check for yarn.lock changes
      #   id: check_yarn_lock
      #   run: |
      #     git fetch origin master

      #     if git diff --name-only origin/master | grep -q "yarn.lock"; then
      #       echo "yarn_lock_changed=true" >> $GITHUB_OUTPUT
      #     else
      #       echo "yarn_lock_changed=false" >> $GITHUB_OUTPUT
      #     fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update and audit packages
          branch: automatic-package-updater
          base: master
          commit-message: Update and audit packages
          delete-branch: false
          assignees: tomguillermou
          reviewers: tomguillermou

      - name: Comment audit summary
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: |
            ## Audit Summary
            ${{ steps.audit_summary.outputs.body }}
